.TH textselect 1 "2024-08-07" "textselect 0.1" "User Commands"
.SH NAME
textselect \- Interactively select lines from a text file and optionally execute a command with the selected lines.
.SH SYNOPSIS
.B textselect
.RB [ \-hvx ] 
.RB [ \-o \ output ]
.I input
.I [command [args...]]
.SH DESCRIPTION
.B textselect
allows users to interactively select lines from a text file. The selected lines can be saved to an output file or passed to a command for execution.
.SH OPTIONS
.TP
.B \-h
Display this help message and exit.
.TP
.B \-v
Invert the selection of lines.
.TP
.B \-o \fIoutput\fR
Specify an output file to save the selected lines.
.SH NAVIGATION AND SELECTION KEYS
.TP
.B UP, LEFT
Move the cursor up.
.TP
.B DOWN, RIGHT
Move the cursor down.
.TP
.B v
Invert the selection of lines.
.TP
.B SPACE
Select or deselect the current line.
.TP
.B ENTER, q
Quit the selection interface.
.SH EXAMPLES
.TP
.B textselect \-o output.txt input.txt
Interactively select lines from \fIinput.txt\fR and save the selected lines to \fIoutput.txt\fR.
.TP
.B textselect input.txt sort
Interactively select lines from \fIinput.txt\fR and pass the selected lines as arguments to the \fBsort\fR command.
.TP
.B textselect \-i input.txt echo \{\}
Interactively select lines from \fIinput.txt\fR and execute the \fBecho\fR command for each selected line, replacing \{\} with the selected line.
.TP
.B textselect \-l input.txt echo
Interactively select lines from \fIinput.txt\fR and execute the \fBecho\fR command for each selected line.
.SH SEE ALSO
.BR sort (1),
.BR echo (1)
.SH AUTHOR
Written by Friedel Schon.
.SH BUGS
Issue bugs at https://github.com/friedelschoen/textselect.

